# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Taylor Marsden
tagline:          Web writer. Blogger. Copywriter.
description:      My homepage.
url:              http://taylormarsden.com

author:
  name:           Taylor Marsden
  url:            https://twitter.com/tkmars

paginate:         1

# Links
links:
  - name:         Creative Content
    url:          /creative-content
  - name:         Ad Copy
    url:          /adcopy
  - name:         Blogging
    url:          /blogging
  - name:         Contact
    url:          /contact

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/tkmars/tkmars.github.io
